# Generated by Django 5.1.5 on 2025-03-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_comments_alter_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
    ]
