# Generated by Django 5.1.5 on 2025-03-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_timestamp_comment_created_at_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
    ]
